service: post-api

plugins:
  - serverless-export-env

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    USERS_TABLE: ${cf:backend-${self:provider.stage}.UsersTableName}
    POSTS_TABLE: ${self:custom.projectPrefix}-posts-table-${self:provider.stage}
    CATEGORIES_TABLE: ${self:custom.projectPrefix}-categories-table-${self:provider.stage}
    COMMENTS_TABLE: ${self:custom.projectPrefix}-comments-table-${self:provider.stage}
    LIKES_TABLE: ${self:custom.projectPrefix}-likes-table-${self:provider.stage}
    HASHTAGS_TABLE: ${self:custom.projectPrefix}-hashtags-table-${self:provider.stage}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    COGNITO_CLIENT_SECRET: ${env:COGNITO_CLIENT_SECRET}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.projectPrefix}-posts-table-${self:provider.stage}

custom:
  projectPrefix: egetwhy

functions:
  createPost:
    handler: src/server.handler
    events:
      - http:
          path: api/posts
          method: post

resources:
  Resources:
    PostsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.environment.POSTS_TABLE}
        AttributeDefinitions:
          - AttributeName: "PostID"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "PostID"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    CategoriesTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.environment.CATEGORIES_TABLE}
        AttributeDefinitions:
          - AttributeName: "CategoryID"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "CategoryID"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

package:
  individually: true
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**
    - README.md
    - package-lock.json
