org: lokytech
app: egetwhy-app
service: backend

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'} # default stage is 'dev'
  environment:
    USERS_TABLE: ${self:custom.tableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

custom:
  tableName: "users-table-${self:provider.stage}"

package:
  exclude:
    - node_modules/**
    - dist/**
    - .serverless/**
    - .git/**
