org: lokytech
app: egetwhy-app
service: backend

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'} # default stage is 'dev'
  environment:
    USERS_TABLE: ${self:custom.tableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]

functions:
  getUser:
    handler: src/users/handler.getUser
    events:
      - http:
          path: users/{userId}
          method: get
  createUser:
    handler: src/users/handler.createUser
    events:
      - http:
          path: users
          method: post
  s3EventHandler:
    handler: src/events/s3EventHandler.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
  dynamoEventHandler:
    handler: src/events/dynamoEventHandler.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - UsersTable
              - StreamArn

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TableName: ${self:custom.tableName}
    S3BucketMyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: egetwhy-bucket

custom:
  tableName: "users-table-${self:provider.stage}"
  bucketName: ${self:custom.bucketNames.${self:provider.stage}}

  bucketNames:
    dev: e-getwhy-bucket-dev
    production: e-getwhy-bucket-prod

package:
  exclude:
    - node_modules/**
    - dist/**
    - .serverless/**
    - .git/**
